
package StateCapitals;

import java.awt.Color;
import java.awt.Toolkit;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 Class          EditPlayer
 File           EditPlayer.java
 Description    A class used to edit selected player
 Project	Project1--State Capitals Quiz
 Platform	jdk 1.8.0_241; NetBeans IDE 11.3; Windows 10
 * @author      <i>Leanne Vu</i>
 * Date     	4/22/2021
 * @version     1.0.0
 * @see         java.awt.Color
 *</pre>
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class EditPlayer extends javax.swing.JDialog {
    private Player newPlayers;  //new Player obj are create
    private boolean error = false;
    private String errorMessage = " ";//Error message
    private final Color white = Color.WHITE; //Default background color for input textfield
    private final Color pink = Color.PINK; //Default background color for bad input textfield
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Constructor      EditPlayer()-default constructor
     * Description      Create an instance of the GUI form, set the default 
     *                  JButton to be saveJButton, set icone image center form
     *                  and set the JDialog to modal.
     * @param           parent java.awt.Frame p
     * @param           modal  boolean 
     * @author          <i>Leanne Vu</i>
     * Date             4/22/2021
     * History Log     
     *</pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**/
    public EditPlayer(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(saveJButton);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(
                "src/CapitalImages/State Capitals Small.png"));
        // center the application
        setLocationRelativeTo(null);
        nameJTextField.requestFocus(); //focus to nameJTextField
        newPlayers = null;
        setAlwaysOnTop(true);
        setModal(true);
    }

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Constructor      EditPlayers()-overloaded constructor
     * Description      Calls default constructor tolerate an instance of the GUI
     *                  form and populate data fields for the selected player
     * @param           player Player
     * @author          <i>Leanne Vu</i>
     * Date             4/22/2021
     *</pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
        public EditPlayer(Player player){
            //this();
            nameJTextField.setText(player.getName());
            ageJTextField.setText(Integer.toString(player.getAge()));
            correctAnswersJTextField.setText(Integer.toString(player.getCorrectAnswers()));
            numOfQuestionsJTextField.setText(Integer.toString(player.getNumOfQuestions()));
            nameJTextField.requestFocus();
        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JPanel();
        titleJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        exitJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        inputJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        ageJLabel = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        correctAnswersJLabel = new javax.swing.JLabel();
        correctAnswersJTextField = new javax.swing.JTextField();
        numOfQuestionsJLabel = new javax.swing.JLabel();
        numOfQuestionsJTextField = new javax.swing.JTextField();

        displayJPanel.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Player");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Edit Player");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapitalImages/Atlanta.jpg"))); // NOI18N

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(73, 73, 73))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(titleJPanel, java.awt.BorderLayout.NORTH);

        exitJButton.setBackground(new java.awt.Color(102, 255, 153));
        exitJButton.setMnemonic('C');
        exitJButton.setText("Cancel");
        exitJButton.setToolTipText("");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        saveJButton.setBackground(new java.awt.Color(102, 255, 153));
        saveJButton.setMnemonic('S');
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(exitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitJButton)
                    .addComponent(saveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(controlPanel, java.awt.BorderLayout.SOUTH);

        inputJPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameJLabel.setText("Name of Player:");
        inputJPanel.add(nameJLabel);

        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusLost(evt);
            }
        });
        inputJPanel.add(nameJTextField);

        ageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageJLabel.setText("Age:");
        inputJPanel.add(ageJLabel);

        ageJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageJTextFieldFocusLost(evt);
            }
        });
        inputJPanel.add(ageJTextField);

        correctAnswersJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        correctAnswersJLabel.setText("Correct Answers:");
        inputJPanel.add(correctAnswersJLabel);

        correctAnswersJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                correctAnswersJTextFieldFocusLost(evt);
            }
        });
        inputJPanel.add(correctAnswersJTextField);

        numOfQuestionsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numOfQuestionsJLabel.setText("Total Number of Questions:");
        inputJPanel.add(numOfQuestionsJLabel);

        numOfQuestionsJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numOfQuestionsJTextFieldFocusLost(evt);
            }
        });
        inputJPanel.add(numOfQuestionsJTextField);

        getContentPane().add(inputJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        saveJButtonActionPerformed()
    * Description   Event handler to create a new city; provided data inputed
    *               validation.
    * @param        evt ActionWvent
    * @see          java.awt.event.ActionEvent
     * Date         4/22/2021
     * History log  
     * @author	<i>Leanne Vu</i>
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
         String name;
         int age;
         int correctAnswers;
         int numOfQuestions;
         
         //Read all input as a String
         String playerName = nameJTextField.getText();
         String playerAge = ageJTextField.getText();
         String playerCorrectAnswers = correctAnswersJTextField.getText();
         String playerNumOfQuestions = numOfQuestionsJTextField.getText();         
         //call appropriate Validation method to verifid input
         if (!Validation.isValidName(playerName)){
             errorMessage += "Invalid Player Name \n";
              nameJTextField.requestFocus();
              error = true;
              nameJTextField.setToolTipText("--Invalid Player Name") ;
         } else if (!Validation.isInteger(playerAge, 0 , 100)){
              errorMessage += "Invalid Age\n";
              correctAnswersJTextField.requestFocus();
              error = true;
              correctAnswersJTextField.setToolTipText("--Invalid Age") ;
         }else if (!Validation.isInteger(playerCorrectAnswers, 0, 100)){
              errorMessage += "Invalid Correct Answers\n";
              ageJTextField.requestFocus();
              error = true;
              ageJTextField.setToolTipText("--Invalid Correct Answers") ;
         } else if (!Validation.isInteger(playerNumOfQuestions, 0, 100)){
              errorMessage += "Invalid Correct Answers\n";
              ageJTextField.requestFocus();
              error = true;
              ageJTextField.setToolTipText("--Invalid Correct Answers") ;
         } else 
            error = false;
         if (!error)  // all input valid
         {
             try{
                name =  nameJTextField.getText();
                age = Integer.parseInt(ageJTextField.getText());
                correctAnswers = Integer.parseInt( correctAnswersJTextField.getText());
                numOfQuestions = Integer.parseInt(numOfQuestionsJTextField.getText());
                newPlayers = new Player(name, age, correctAnswers, numOfQuestions);
                this.dispose(); //close form
             
             }catch(Exception ex){
                 throw new RuntimeException("Error parsing input");
             }
         }
    }//GEN-LAST:event_saveJButtonActionPerformed
   
   /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Method        exitJButtonActionPerformed()
     * Description   Event handler for cancel adding a new city: do nothing and
     *               leave newCity as null.
     * @param        evt ActionWvent
     * @see          java.awt.event.ActionEvent
     * Date         4/22/2021
     * History log  
     * @author	<i>Leanne Vu</i>
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitJButtonActionPerformed
   
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Method        nameJTextFieldFocusLost() 
     * Description   Event handler for the nameJTextField. It changes colors
     *               if input is not a valid name.
     * @parem        evt FocusEvent
     * @author       <i>Leanne Vu</i>	
     * Date          4/22/2021
     *</pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void nameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusLost
        // Set background textfield color
        String input = nameJTextField.getText();
        if (Validation.isValidName(input))
            nameJTextField.setBackground(white);
        else
            nameJTextField.setBackground(pink);
    }//GEN-LAST:event_nameJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Method        ageJTextFieldFocusLost() 
     * Description   Event handler for the ageJTextFieldFocusLost.
     *               It changes colors if input is not a valid name.
     * @parem        evt FocusEvent
     * @author       <i>Leanne Vu</i>	
     * Date          4/22/2021
     *</pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void ageJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageJTextFieldFocusLost
         // Set background textfield color
        String input = ageJTextField.getText();
        if (Validation.isInteger(input, 0, 100))
            ageJTextField.setBackground(white);
        else
            ageJTextField.setBackground(pink);
    }//GEN-LAST:event_ageJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Method        balanceJTextFieldFocusLost() 
     * Description   Event handler for the balanceJTextFieldFocusLost().
     *               It changes colors if input is not a valid name.
     * @parem        evt FocusEvent
     * @author       <i>Leanne Vu</i>	
     * Date          4/22/2021
     *</pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void correctAnswersJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correctAnswersJTextFieldFocusLost
                // Set background textfield color
        String input = correctAnswersJTextField.getText();
        if (Validation.isInteger(input, 0 , 100))
            correctAnswersJTextField.setBackground(white);
        else
            correctAnswersJTextField.setBackground(pink);
    }//GEN-LAST:event_correctAnswersJTextFieldFocusLost

    private void numOfQuestionsJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numOfQuestionsJTextFieldFocusLost
                // Set background textfield color
        String input = numOfQuestionsJTextField.getText();
        if (Validation.isInteger(input, 0 , 100))
            correctAnswersJTextField.setBackground(white);
        else
            correctAnswersJTextField.setBackground(pink);
    }//GEN-LAST:event_numOfQuestionsJTextFieldFocusLost



   /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method       getPlayer()
     * Description  Get method to return newPlayer
     * @author      <i>Leanne Vu</i>
     * @return      newOperas String
     * Date         4/22/2021
     *</pre>   
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public Player getPlayers(){
            return newPlayers;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel correctAnswersJLabel;
    private javax.swing.JTextField correctAnswersJTextField;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JButton exitJButton;
    private javax.swing.JPanel inputJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel numOfQuestionsJLabel;
    private javax.swing.JTextField numOfQuestionsJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}
